/*
Plentymarkets-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ItemShippingProfileRequest struct for ItemShippingProfileRequest
type ItemShippingProfileRequest struct {
	Id *int32 `json:"id,omitempty"`
	ItemId *int32 `json:"itemId,omitempty"`
	ProfileId *string `json:"profileId,omitempty"`
}

// NewItemShippingProfileRequest instantiates a new ItemShippingProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemShippingProfileRequest() *ItemShippingProfileRequest {
	this := ItemShippingProfileRequest{}
	return &this
}

// NewItemShippingProfileRequestWithDefaults instantiates a new ItemShippingProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemShippingProfileRequestWithDefaults() *ItemShippingProfileRequest {
	this := ItemShippingProfileRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ItemShippingProfileRequest) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemShippingProfileRequest) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ItemShippingProfileRequest) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ItemShippingProfileRequest) SetId(v int32) {
	o.Id = &v
}

// GetItemId returns the ItemId field value if set, zero value otherwise.
func (o *ItemShippingProfileRequest) GetItemId() int32 {
	if o == nil || o.ItemId == nil {
		var ret int32
		return ret
	}
	return *o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemShippingProfileRequest) GetItemIdOk() (*int32, bool) {
	if o == nil || o.ItemId == nil {
		return nil, false
	}
	return o.ItemId, true
}

// HasItemId returns a boolean if a field has been set.
func (o *ItemShippingProfileRequest) HasItemId() bool {
	if o != nil && o.ItemId != nil {
		return true
	}

	return false
}

// SetItemId gets a reference to the given int32 and assigns it to the ItemId field.
func (o *ItemShippingProfileRequest) SetItemId(v int32) {
	o.ItemId = &v
}

// GetProfileId returns the ProfileId field value if set, zero value otherwise.
func (o *ItemShippingProfileRequest) GetProfileId() string {
	if o == nil || o.ProfileId == nil {
		var ret string
		return ret
	}
	return *o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemShippingProfileRequest) GetProfileIdOk() (*string, bool) {
	if o == nil || o.ProfileId == nil {
		return nil, false
	}
	return o.ProfileId, true
}

// HasProfileId returns a boolean if a field has been set.
func (o *ItemShippingProfileRequest) HasProfileId() bool {
	if o != nil && o.ProfileId != nil {
		return true
	}

	return false
}

// SetProfileId gets a reference to the given string and assigns it to the ProfileId field.
func (o *ItemShippingProfileRequest) SetProfileId(v string) {
	o.ProfileId = &v
}

func (o ItemShippingProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.ItemId != nil {
		toSerialize["itemId"] = o.ItemId
	}
	if o.ProfileId != nil {
		toSerialize["profileId"] = o.ProfileId
	}
	return json.Marshal(toSerialize)
}

type NullableItemShippingProfileRequest struct {
	value *ItemShippingProfileRequest
	isSet bool
}

func (v NullableItemShippingProfileRequest) Get() *ItemShippingProfileRequest {
	return v.value
}

func (v *NullableItemShippingProfileRequest) Set(val *ItemShippingProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableItemShippingProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableItemShippingProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemShippingProfileRequest(val *ItemShippingProfileRequest) *NullableItemShippingProfileRequest {
	return &NullableItemShippingProfileRequest{value: val, isSet: true}
}

func (v NullableItemShippingProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemShippingProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


