/*
Plentymarkets-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	// Current page of the response
	Page *int32 `json:"page,omitempty"`
	// The total number of entries in the response
	TotalsCount *int32 `json:"totalsCount,omitempty"`
	// Flag that indicates if the page shown is the last page of the response
	IsLastPage *bool `json:"isLastPage,omitempty"`
	// The last page number
	LastPageNumber *int32 `json:"lastPageNumber,omitempty"`
	// The index of the first item of the current page result
	FirstOnPage *int32 `json:"firstOnPage,omitempty"`
	// The index of the last item of the current page result
	LastOnPage *int32 `json:"lastOnPage,omitempty"`
	// The requested amount of items per result page
	ItemsPerPage *int32 `json:"itemsPerPage,omitempty"`
	// List of Variation
	Entries *[]PimVariation `json:"entries,omitempty"`
}

// NewInlineResponse200 instantiates a new InlineResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200() *InlineResponse200 {
	this := InlineResponse200{}
	return &this
}

// NewInlineResponse200WithDefaults instantiates a new InlineResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200WithDefaults() *InlineResponse200 {
	this := InlineResponse200{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *InlineResponse200) GetPage() int32 {
	if o == nil || o.Page == nil {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetPageOk() (*int32, bool) {
	if o == nil || o.Page == nil {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *InlineResponse200) HasPage() bool {
	if o != nil && o.Page != nil {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *InlineResponse200) SetPage(v int32) {
	o.Page = &v
}

// GetTotalsCount returns the TotalsCount field value if set, zero value otherwise.
func (o *InlineResponse200) GetTotalsCount() int32 {
	if o == nil || o.TotalsCount == nil {
		var ret int32
		return ret
	}
	return *o.TotalsCount
}

// GetTotalsCountOk returns a tuple with the TotalsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetTotalsCountOk() (*int32, bool) {
	if o == nil || o.TotalsCount == nil {
		return nil, false
	}
	return o.TotalsCount, true
}

// HasTotalsCount returns a boolean if a field has been set.
func (o *InlineResponse200) HasTotalsCount() bool {
	if o != nil && o.TotalsCount != nil {
		return true
	}

	return false
}

// SetTotalsCount gets a reference to the given int32 and assigns it to the TotalsCount field.
func (o *InlineResponse200) SetTotalsCount(v int32) {
	o.TotalsCount = &v
}

// GetIsLastPage returns the IsLastPage field value if set, zero value otherwise.
func (o *InlineResponse200) GetIsLastPage() bool {
	if o == nil || o.IsLastPage == nil {
		var ret bool
		return ret
	}
	return *o.IsLastPage
}

// GetIsLastPageOk returns a tuple with the IsLastPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetIsLastPageOk() (*bool, bool) {
	if o == nil || o.IsLastPage == nil {
		return nil, false
	}
	return o.IsLastPage, true
}

// HasIsLastPage returns a boolean if a field has been set.
func (o *InlineResponse200) HasIsLastPage() bool {
	if o != nil && o.IsLastPage != nil {
		return true
	}

	return false
}

// SetIsLastPage gets a reference to the given bool and assigns it to the IsLastPage field.
func (o *InlineResponse200) SetIsLastPage(v bool) {
	o.IsLastPage = &v
}

// GetLastPageNumber returns the LastPageNumber field value if set, zero value otherwise.
func (o *InlineResponse200) GetLastPageNumber() int32 {
	if o == nil || o.LastPageNumber == nil {
		var ret int32
		return ret
	}
	return *o.LastPageNumber
}

// GetLastPageNumberOk returns a tuple with the LastPageNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetLastPageNumberOk() (*int32, bool) {
	if o == nil || o.LastPageNumber == nil {
		return nil, false
	}
	return o.LastPageNumber, true
}

// HasLastPageNumber returns a boolean if a field has been set.
func (o *InlineResponse200) HasLastPageNumber() bool {
	if o != nil && o.LastPageNumber != nil {
		return true
	}

	return false
}

// SetLastPageNumber gets a reference to the given int32 and assigns it to the LastPageNumber field.
func (o *InlineResponse200) SetLastPageNumber(v int32) {
	o.LastPageNumber = &v
}

// GetFirstOnPage returns the FirstOnPage field value if set, zero value otherwise.
func (o *InlineResponse200) GetFirstOnPage() int32 {
	if o == nil || o.FirstOnPage == nil {
		var ret int32
		return ret
	}
	return *o.FirstOnPage
}

// GetFirstOnPageOk returns a tuple with the FirstOnPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetFirstOnPageOk() (*int32, bool) {
	if o == nil || o.FirstOnPage == nil {
		return nil, false
	}
	return o.FirstOnPage, true
}

// HasFirstOnPage returns a boolean if a field has been set.
func (o *InlineResponse200) HasFirstOnPage() bool {
	if o != nil && o.FirstOnPage != nil {
		return true
	}

	return false
}

// SetFirstOnPage gets a reference to the given int32 and assigns it to the FirstOnPage field.
func (o *InlineResponse200) SetFirstOnPage(v int32) {
	o.FirstOnPage = &v
}

// GetLastOnPage returns the LastOnPage field value if set, zero value otherwise.
func (o *InlineResponse200) GetLastOnPage() int32 {
	if o == nil || o.LastOnPage == nil {
		var ret int32
		return ret
	}
	return *o.LastOnPage
}

// GetLastOnPageOk returns a tuple with the LastOnPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetLastOnPageOk() (*int32, bool) {
	if o == nil || o.LastOnPage == nil {
		return nil, false
	}
	return o.LastOnPage, true
}

// HasLastOnPage returns a boolean if a field has been set.
func (o *InlineResponse200) HasLastOnPage() bool {
	if o != nil && o.LastOnPage != nil {
		return true
	}

	return false
}

// SetLastOnPage gets a reference to the given int32 and assigns it to the LastOnPage field.
func (o *InlineResponse200) SetLastOnPage(v int32) {
	o.LastOnPage = &v
}

// GetItemsPerPage returns the ItemsPerPage field value if set, zero value otherwise.
func (o *InlineResponse200) GetItemsPerPage() int32 {
	if o == nil || o.ItemsPerPage == nil {
		var ret int32
		return ret
	}
	return *o.ItemsPerPage
}

// GetItemsPerPageOk returns a tuple with the ItemsPerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetItemsPerPageOk() (*int32, bool) {
	if o == nil || o.ItemsPerPage == nil {
		return nil, false
	}
	return o.ItemsPerPage, true
}

// HasItemsPerPage returns a boolean if a field has been set.
func (o *InlineResponse200) HasItemsPerPage() bool {
	if o != nil && o.ItemsPerPage != nil {
		return true
	}

	return false
}

// SetItemsPerPage gets a reference to the given int32 and assigns it to the ItemsPerPage field.
func (o *InlineResponse200) SetItemsPerPage(v int32) {
	o.ItemsPerPage = &v
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *InlineResponse200) GetEntries() []PimVariation {
	if o == nil || o.Entries == nil {
		var ret []PimVariation
		return ret
	}
	return *o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetEntriesOk() (*[]PimVariation, bool) {
	if o == nil || o.Entries == nil {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *InlineResponse200) HasEntries() bool {
	if o != nil && o.Entries != nil {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []PimVariation and assigns it to the Entries field.
func (o *InlineResponse200) SetEntries(v []PimVariation) {
	o.Entries = &v
}

func (o InlineResponse200) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Page != nil {
		toSerialize["page"] = o.Page
	}
	if o.TotalsCount != nil {
		toSerialize["totalsCount"] = o.TotalsCount
	}
	if o.IsLastPage != nil {
		toSerialize["isLastPage"] = o.IsLastPage
	}
	if o.LastPageNumber != nil {
		toSerialize["lastPageNumber"] = o.LastPageNumber
	}
	if o.FirstOnPage != nil {
		toSerialize["firstOnPage"] = o.FirstOnPage
	}
	if o.LastOnPage != nil {
		toSerialize["lastOnPage"] = o.LastOnPage
	}
	if o.ItemsPerPage != nil {
		toSerialize["itemsPerPage"] = o.ItemsPerPage
	}
	if o.Entries != nil {
		toSerialize["entries"] = o.Entries
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200 struct {
	value *InlineResponse200
	isSet bool
}

func (v NullableInlineResponse200) Get() *InlineResponse200 {
	return v.value
}

func (v *NullableInlineResponse200) Set(val *InlineResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200(val *InlineResponse200) *NullableInlineResponse200 {
	return &NullableInlineResponse200{value: val, isSet: true}
}

func (v NullableInlineResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


