/*
Plentymarkets-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// OrderDocumentPivot struct for OrderDocumentPivot
type OrderDocumentPivot struct {
	PlentyDocumentReferenceValue *string `json:"plenty_document_reference_value,omitempty"`
	PlentyDocumentReferenceDocumentId *string `json:"plenty_document_reference_document_id,omitempty"`
}

// NewOrderDocumentPivot instantiates a new OrderDocumentPivot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderDocumentPivot() *OrderDocumentPivot {
	this := OrderDocumentPivot{}
	return &this
}

// NewOrderDocumentPivotWithDefaults instantiates a new OrderDocumentPivot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderDocumentPivotWithDefaults() *OrderDocumentPivot {
	this := OrderDocumentPivot{}
	return &this
}

// GetPlentyDocumentReferenceValue returns the PlentyDocumentReferenceValue field value if set, zero value otherwise.
func (o *OrderDocumentPivot) GetPlentyDocumentReferenceValue() string {
	if o == nil || o.PlentyDocumentReferenceValue == nil {
		var ret string
		return ret
	}
	return *o.PlentyDocumentReferenceValue
}

// GetPlentyDocumentReferenceValueOk returns a tuple with the PlentyDocumentReferenceValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDocumentPivot) GetPlentyDocumentReferenceValueOk() (*string, bool) {
	if o == nil || o.PlentyDocumentReferenceValue == nil {
		return nil, false
	}
	return o.PlentyDocumentReferenceValue, true
}

// HasPlentyDocumentReferenceValue returns a boolean if a field has been set.
func (o *OrderDocumentPivot) HasPlentyDocumentReferenceValue() bool {
	if o != nil && o.PlentyDocumentReferenceValue != nil {
		return true
	}

	return false
}

// SetPlentyDocumentReferenceValue gets a reference to the given string and assigns it to the PlentyDocumentReferenceValue field.
func (o *OrderDocumentPivot) SetPlentyDocumentReferenceValue(v string) {
	o.PlentyDocumentReferenceValue = &v
}

// GetPlentyDocumentReferenceDocumentId returns the PlentyDocumentReferenceDocumentId field value if set, zero value otherwise.
func (o *OrderDocumentPivot) GetPlentyDocumentReferenceDocumentId() string {
	if o == nil || o.PlentyDocumentReferenceDocumentId == nil {
		var ret string
		return ret
	}
	return *o.PlentyDocumentReferenceDocumentId
}

// GetPlentyDocumentReferenceDocumentIdOk returns a tuple with the PlentyDocumentReferenceDocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDocumentPivot) GetPlentyDocumentReferenceDocumentIdOk() (*string, bool) {
	if o == nil || o.PlentyDocumentReferenceDocumentId == nil {
		return nil, false
	}
	return o.PlentyDocumentReferenceDocumentId, true
}

// HasPlentyDocumentReferenceDocumentId returns a boolean if a field has been set.
func (o *OrderDocumentPivot) HasPlentyDocumentReferenceDocumentId() bool {
	if o != nil && o.PlentyDocumentReferenceDocumentId != nil {
		return true
	}

	return false
}

// SetPlentyDocumentReferenceDocumentId gets a reference to the given string and assigns it to the PlentyDocumentReferenceDocumentId field.
func (o *OrderDocumentPivot) SetPlentyDocumentReferenceDocumentId(v string) {
	o.PlentyDocumentReferenceDocumentId = &v
}

func (o OrderDocumentPivot) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PlentyDocumentReferenceValue != nil {
		toSerialize["plenty_document_reference_value"] = o.PlentyDocumentReferenceValue
	}
	if o.PlentyDocumentReferenceDocumentId != nil {
		toSerialize["plenty_document_reference_document_id"] = o.PlentyDocumentReferenceDocumentId
	}
	return json.Marshal(toSerialize)
}

type NullableOrderDocumentPivot struct {
	value *OrderDocumentPivot
	isSet bool
}

func (v NullableOrderDocumentPivot) Get() *OrderDocumentPivot {
	return v.value
}

func (v *NullableOrderDocumentPivot) Set(val *OrderDocumentPivot) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderDocumentPivot) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderDocumentPivot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderDocumentPivot(val *OrderDocumentPivot) *NullableOrderDocumentPivot {
	return &NullableOrderDocumentPivot{value: val, isSet: true}
}

func (v NullableOrderDocumentPivot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderDocumentPivot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


