/*
Plentymarkets-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// OrderItem struct for OrderItem
type OrderItem struct {
	Id *int32 `json:"id,omitempty"`
	OrderId *int32 `json:"orderId,omitempty"`
	TypeId *int32 `json:"typeId,omitempty"`
	ReferrerId *float32 `json:"referrerId,omitempty"`
	ItemVariationId *int32 `json:"itemVariationId,omitempty"`
	Quantity *float32 `json:"quantity,omitempty"`
	OrderItemName *string `json:"orderItemName,omitempty"`
	AttributeValues *string `json:"attributeValues,omitempty"`
	ShippingProfileId *int32 `json:"shippingProfileId,omitempty"`
	CountryVatId *int32 `json:"countryVatId,omitempty"`
	VatField *int32 `json:"vatField,omitempty"`
	VatRate *float32 `json:"vatRate,omitempty"`
	Position *int32 `json:"position,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	WarehouseId *int32 `json:"warehouseId,omitempty"`
	Variation *Variation `json:"variation,omitempty"`
	VariationBarcodes *[]VariationBarcode `json:"variationBarcodes,omitempty"`
}

// NewOrderItem instantiates a new OrderItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderItem() *OrderItem {
	this := OrderItem{}
	return &this
}

// NewOrderItemWithDefaults instantiates a new OrderItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderItemWithDefaults() *OrderItem {
	this := OrderItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrderItem) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrderItem) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *OrderItem) SetId(v int32) {
	o.Id = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *OrderItem) GetOrderId() int32 {
	if o == nil || o.OrderId == nil {
		var ret int32
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetOrderIdOk() (*int32, bool) {
	if o == nil || o.OrderId == nil {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *OrderItem) HasOrderId() bool {
	if o != nil && o.OrderId != nil {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given int32 and assigns it to the OrderId field.
func (o *OrderItem) SetOrderId(v int32) {
	o.OrderId = &v
}

// GetTypeId returns the TypeId field value if set, zero value otherwise.
func (o *OrderItem) GetTypeId() int32 {
	if o == nil || o.TypeId == nil {
		var ret int32
		return ret
	}
	return *o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetTypeIdOk() (*int32, bool) {
	if o == nil || o.TypeId == nil {
		return nil, false
	}
	return o.TypeId, true
}

// HasTypeId returns a boolean if a field has been set.
func (o *OrderItem) HasTypeId() bool {
	if o != nil && o.TypeId != nil {
		return true
	}

	return false
}

// SetTypeId gets a reference to the given int32 and assigns it to the TypeId field.
func (o *OrderItem) SetTypeId(v int32) {
	o.TypeId = &v
}

// GetReferrerId returns the ReferrerId field value if set, zero value otherwise.
func (o *OrderItem) GetReferrerId() float32 {
	if o == nil || o.ReferrerId == nil {
		var ret float32
		return ret
	}
	return *o.ReferrerId
}

// GetReferrerIdOk returns a tuple with the ReferrerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetReferrerIdOk() (*float32, bool) {
	if o == nil || o.ReferrerId == nil {
		return nil, false
	}
	return o.ReferrerId, true
}

// HasReferrerId returns a boolean if a field has been set.
func (o *OrderItem) HasReferrerId() bool {
	if o != nil && o.ReferrerId != nil {
		return true
	}

	return false
}

// SetReferrerId gets a reference to the given float32 and assigns it to the ReferrerId field.
func (o *OrderItem) SetReferrerId(v float32) {
	o.ReferrerId = &v
}

// GetItemVariationId returns the ItemVariationId field value if set, zero value otherwise.
func (o *OrderItem) GetItemVariationId() int32 {
	if o == nil || o.ItemVariationId == nil {
		var ret int32
		return ret
	}
	return *o.ItemVariationId
}

// GetItemVariationIdOk returns a tuple with the ItemVariationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetItemVariationIdOk() (*int32, bool) {
	if o == nil || o.ItemVariationId == nil {
		return nil, false
	}
	return o.ItemVariationId, true
}

// HasItemVariationId returns a boolean if a field has been set.
func (o *OrderItem) HasItemVariationId() bool {
	if o != nil && o.ItemVariationId != nil {
		return true
	}

	return false
}

// SetItemVariationId gets a reference to the given int32 and assigns it to the ItemVariationId field.
func (o *OrderItem) SetItemVariationId(v int32) {
	o.ItemVariationId = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *OrderItem) GetQuantity() float32 {
	if o == nil || o.Quantity == nil {
		var ret float32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetQuantityOk() (*float32, bool) {
	if o == nil || o.Quantity == nil {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *OrderItem) HasQuantity() bool {
	if o != nil && o.Quantity != nil {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float32 and assigns it to the Quantity field.
func (o *OrderItem) SetQuantity(v float32) {
	o.Quantity = &v
}

// GetOrderItemName returns the OrderItemName field value if set, zero value otherwise.
func (o *OrderItem) GetOrderItemName() string {
	if o == nil || o.OrderItemName == nil {
		var ret string
		return ret
	}
	return *o.OrderItemName
}

// GetOrderItemNameOk returns a tuple with the OrderItemName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetOrderItemNameOk() (*string, bool) {
	if o == nil || o.OrderItemName == nil {
		return nil, false
	}
	return o.OrderItemName, true
}

// HasOrderItemName returns a boolean if a field has been set.
func (o *OrderItem) HasOrderItemName() bool {
	if o != nil && o.OrderItemName != nil {
		return true
	}

	return false
}

// SetOrderItemName gets a reference to the given string and assigns it to the OrderItemName field.
func (o *OrderItem) SetOrderItemName(v string) {
	o.OrderItemName = &v
}

// GetAttributeValues returns the AttributeValues field value if set, zero value otherwise.
func (o *OrderItem) GetAttributeValues() string {
	if o == nil || o.AttributeValues == nil {
		var ret string
		return ret
	}
	return *o.AttributeValues
}

// GetAttributeValuesOk returns a tuple with the AttributeValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetAttributeValuesOk() (*string, bool) {
	if o == nil || o.AttributeValues == nil {
		return nil, false
	}
	return o.AttributeValues, true
}

// HasAttributeValues returns a boolean if a field has been set.
func (o *OrderItem) HasAttributeValues() bool {
	if o != nil && o.AttributeValues != nil {
		return true
	}

	return false
}

// SetAttributeValues gets a reference to the given string and assigns it to the AttributeValues field.
func (o *OrderItem) SetAttributeValues(v string) {
	o.AttributeValues = &v
}

// GetShippingProfileId returns the ShippingProfileId field value if set, zero value otherwise.
func (o *OrderItem) GetShippingProfileId() int32 {
	if o == nil || o.ShippingProfileId == nil {
		var ret int32
		return ret
	}
	return *o.ShippingProfileId
}

// GetShippingProfileIdOk returns a tuple with the ShippingProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetShippingProfileIdOk() (*int32, bool) {
	if o == nil || o.ShippingProfileId == nil {
		return nil, false
	}
	return o.ShippingProfileId, true
}

// HasShippingProfileId returns a boolean if a field has been set.
func (o *OrderItem) HasShippingProfileId() bool {
	if o != nil && o.ShippingProfileId != nil {
		return true
	}

	return false
}

// SetShippingProfileId gets a reference to the given int32 and assigns it to the ShippingProfileId field.
func (o *OrderItem) SetShippingProfileId(v int32) {
	o.ShippingProfileId = &v
}

// GetCountryVatId returns the CountryVatId field value if set, zero value otherwise.
func (o *OrderItem) GetCountryVatId() int32 {
	if o == nil || o.CountryVatId == nil {
		var ret int32
		return ret
	}
	return *o.CountryVatId
}

// GetCountryVatIdOk returns a tuple with the CountryVatId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetCountryVatIdOk() (*int32, bool) {
	if o == nil || o.CountryVatId == nil {
		return nil, false
	}
	return o.CountryVatId, true
}

// HasCountryVatId returns a boolean if a field has been set.
func (o *OrderItem) HasCountryVatId() bool {
	if o != nil && o.CountryVatId != nil {
		return true
	}

	return false
}

// SetCountryVatId gets a reference to the given int32 and assigns it to the CountryVatId field.
func (o *OrderItem) SetCountryVatId(v int32) {
	o.CountryVatId = &v
}

// GetVatField returns the VatField field value if set, zero value otherwise.
func (o *OrderItem) GetVatField() int32 {
	if o == nil || o.VatField == nil {
		var ret int32
		return ret
	}
	return *o.VatField
}

// GetVatFieldOk returns a tuple with the VatField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetVatFieldOk() (*int32, bool) {
	if o == nil || o.VatField == nil {
		return nil, false
	}
	return o.VatField, true
}

// HasVatField returns a boolean if a field has been set.
func (o *OrderItem) HasVatField() bool {
	if o != nil && o.VatField != nil {
		return true
	}

	return false
}

// SetVatField gets a reference to the given int32 and assigns it to the VatField field.
func (o *OrderItem) SetVatField(v int32) {
	o.VatField = &v
}

// GetVatRate returns the VatRate field value if set, zero value otherwise.
func (o *OrderItem) GetVatRate() float32 {
	if o == nil || o.VatRate == nil {
		var ret float32
		return ret
	}
	return *o.VatRate
}

// GetVatRateOk returns a tuple with the VatRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetVatRateOk() (*float32, bool) {
	if o == nil || o.VatRate == nil {
		return nil, false
	}
	return o.VatRate, true
}

// HasVatRate returns a boolean if a field has been set.
func (o *OrderItem) HasVatRate() bool {
	if o != nil && o.VatRate != nil {
		return true
	}

	return false
}

// SetVatRate gets a reference to the given float32 and assigns it to the VatRate field.
func (o *OrderItem) SetVatRate(v float32) {
	o.VatRate = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *OrderItem) GetPosition() int32 {
	if o == nil || o.Position == nil {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetPositionOk() (*int32, bool) {
	if o == nil || o.Position == nil {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *OrderItem) HasPosition() bool {
	if o != nil && o.Position != nil {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *OrderItem) SetPosition(v int32) {
	o.Position = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *OrderItem) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *OrderItem) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *OrderItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *OrderItem) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *OrderItem) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *OrderItem) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetWarehouseId returns the WarehouseId field value if set, zero value otherwise.
func (o *OrderItem) GetWarehouseId() int32 {
	if o == nil || o.WarehouseId == nil {
		var ret int32
		return ret
	}
	return *o.WarehouseId
}

// GetWarehouseIdOk returns a tuple with the WarehouseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetWarehouseIdOk() (*int32, bool) {
	if o == nil || o.WarehouseId == nil {
		return nil, false
	}
	return o.WarehouseId, true
}

// HasWarehouseId returns a boolean if a field has been set.
func (o *OrderItem) HasWarehouseId() bool {
	if o != nil && o.WarehouseId != nil {
		return true
	}

	return false
}

// SetWarehouseId gets a reference to the given int32 and assigns it to the WarehouseId field.
func (o *OrderItem) SetWarehouseId(v int32) {
	o.WarehouseId = &v
}

// GetVariation returns the Variation field value if set, zero value otherwise.
func (o *OrderItem) GetVariation() Variation {
	if o == nil || o.Variation == nil {
		var ret Variation
		return ret
	}
	return *o.Variation
}

// GetVariationOk returns a tuple with the Variation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetVariationOk() (*Variation, bool) {
	if o == nil || o.Variation == nil {
		return nil, false
	}
	return o.Variation, true
}

// HasVariation returns a boolean if a field has been set.
func (o *OrderItem) HasVariation() bool {
	if o != nil && o.Variation != nil {
		return true
	}

	return false
}

// SetVariation gets a reference to the given Variation and assigns it to the Variation field.
func (o *OrderItem) SetVariation(v Variation) {
	o.Variation = &v
}

// GetVariationBarcodes returns the VariationBarcodes field value if set, zero value otherwise.
func (o *OrderItem) GetVariationBarcodes() []VariationBarcode {
	if o == nil || o.VariationBarcodes == nil {
		var ret []VariationBarcode
		return ret
	}
	return *o.VariationBarcodes
}

// GetVariationBarcodesOk returns a tuple with the VariationBarcodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItem) GetVariationBarcodesOk() (*[]VariationBarcode, bool) {
	if o == nil || o.VariationBarcodes == nil {
		return nil, false
	}
	return o.VariationBarcodes, true
}

// HasVariationBarcodes returns a boolean if a field has been set.
func (o *OrderItem) HasVariationBarcodes() bool {
	if o != nil && o.VariationBarcodes != nil {
		return true
	}

	return false
}

// SetVariationBarcodes gets a reference to the given []VariationBarcode and assigns it to the VariationBarcodes field.
func (o *OrderItem) SetVariationBarcodes(v []VariationBarcode) {
	o.VariationBarcodes = &v
}

func (o OrderItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.OrderId != nil {
		toSerialize["orderId"] = o.OrderId
	}
	if o.TypeId != nil {
		toSerialize["typeId"] = o.TypeId
	}
	if o.ReferrerId != nil {
		toSerialize["referrerId"] = o.ReferrerId
	}
	if o.ItemVariationId != nil {
		toSerialize["itemVariationId"] = o.ItemVariationId
	}
	if o.Quantity != nil {
		toSerialize["quantity"] = o.Quantity
	}
	if o.OrderItemName != nil {
		toSerialize["orderItemName"] = o.OrderItemName
	}
	if o.AttributeValues != nil {
		toSerialize["attributeValues"] = o.AttributeValues
	}
	if o.ShippingProfileId != nil {
		toSerialize["shippingProfileId"] = o.ShippingProfileId
	}
	if o.CountryVatId != nil {
		toSerialize["countryVatId"] = o.CountryVatId
	}
	if o.VatField != nil {
		toSerialize["vatField"] = o.VatField
	}
	if o.VatRate != nil {
		toSerialize["vatRate"] = o.VatRate
	}
	if o.Position != nil {
		toSerialize["position"] = o.Position
	}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.WarehouseId != nil {
		toSerialize["warehouseId"] = o.WarehouseId
	}
	if o.Variation != nil {
		toSerialize["variation"] = o.Variation
	}
	if o.VariationBarcodes != nil {
		toSerialize["variationBarcodes"] = o.VariationBarcodes
	}
	return json.Marshal(toSerialize)
}

type NullableOrderItem struct {
	value *OrderItem
	isSet bool
}

func (v NullableOrderItem) Get() *OrderItem {
	return v.value
}

func (v *NullableOrderItem) Set(val *OrderItem) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderItem) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderItem(val *OrderItem) *NullableOrderItem {
	return &NullableOrderItem{value: val, isSet: true}
}

func (v NullableOrderItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


