/*
Plentymarkets-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// VariationPagination pagination response containing variations
type VariationPagination struct {
	Page *int32 `json:"page,omitempty"`
	TotalsCount *int32 `json:"totalsCount,omitempty"`
	IsLastPage *bool `json:"isLastPage,omitempty"`
	LastPageNumber *int32 `json:"lastPageNumber,omitempty"`
	FirstOnPage *int32 `json:"firstOnPage,omitempty"`
	LastOnPage *int32 `json:"lastOnPage,omitempty"`
	ItemsPerPage *int32 `json:"itemsPerPage,omitempty"`
	Entries *[]Variation `json:"entries,omitempty"`
}

// NewVariationPagination instantiates a new VariationPagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariationPagination() *VariationPagination {
	this := VariationPagination{}
	return &this
}

// NewVariationPaginationWithDefaults instantiates a new VariationPagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariationPaginationWithDefaults() *VariationPagination {
	this := VariationPagination{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *VariationPagination) GetPage() int32 {
	if o == nil || o.Page == nil {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariationPagination) GetPageOk() (*int32, bool) {
	if o == nil || o.Page == nil {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *VariationPagination) HasPage() bool {
	if o != nil && o.Page != nil {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *VariationPagination) SetPage(v int32) {
	o.Page = &v
}

// GetTotalsCount returns the TotalsCount field value if set, zero value otherwise.
func (o *VariationPagination) GetTotalsCount() int32 {
	if o == nil || o.TotalsCount == nil {
		var ret int32
		return ret
	}
	return *o.TotalsCount
}

// GetTotalsCountOk returns a tuple with the TotalsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariationPagination) GetTotalsCountOk() (*int32, bool) {
	if o == nil || o.TotalsCount == nil {
		return nil, false
	}
	return o.TotalsCount, true
}

// HasTotalsCount returns a boolean if a field has been set.
func (o *VariationPagination) HasTotalsCount() bool {
	if o != nil && o.TotalsCount != nil {
		return true
	}

	return false
}

// SetTotalsCount gets a reference to the given int32 and assigns it to the TotalsCount field.
func (o *VariationPagination) SetTotalsCount(v int32) {
	o.TotalsCount = &v
}

// GetIsLastPage returns the IsLastPage field value if set, zero value otherwise.
func (o *VariationPagination) GetIsLastPage() bool {
	if o == nil || o.IsLastPage == nil {
		var ret bool
		return ret
	}
	return *o.IsLastPage
}

// GetIsLastPageOk returns a tuple with the IsLastPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariationPagination) GetIsLastPageOk() (*bool, bool) {
	if o == nil || o.IsLastPage == nil {
		return nil, false
	}
	return o.IsLastPage, true
}

// HasIsLastPage returns a boolean if a field has been set.
func (o *VariationPagination) HasIsLastPage() bool {
	if o != nil && o.IsLastPage != nil {
		return true
	}

	return false
}

// SetIsLastPage gets a reference to the given bool and assigns it to the IsLastPage field.
func (o *VariationPagination) SetIsLastPage(v bool) {
	o.IsLastPage = &v
}

// GetLastPageNumber returns the LastPageNumber field value if set, zero value otherwise.
func (o *VariationPagination) GetLastPageNumber() int32 {
	if o == nil || o.LastPageNumber == nil {
		var ret int32
		return ret
	}
	return *o.LastPageNumber
}

// GetLastPageNumberOk returns a tuple with the LastPageNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariationPagination) GetLastPageNumberOk() (*int32, bool) {
	if o == nil || o.LastPageNumber == nil {
		return nil, false
	}
	return o.LastPageNumber, true
}

// HasLastPageNumber returns a boolean if a field has been set.
func (o *VariationPagination) HasLastPageNumber() bool {
	if o != nil && o.LastPageNumber != nil {
		return true
	}

	return false
}

// SetLastPageNumber gets a reference to the given int32 and assigns it to the LastPageNumber field.
func (o *VariationPagination) SetLastPageNumber(v int32) {
	o.LastPageNumber = &v
}

// GetFirstOnPage returns the FirstOnPage field value if set, zero value otherwise.
func (o *VariationPagination) GetFirstOnPage() int32 {
	if o == nil || o.FirstOnPage == nil {
		var ret int32
		return ret
	}
	return *o.FirstOnPage
}

// GetFirstOnPageOk returns a tuple with the FirstOnPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariationPagination) GetFirstOnPageOk() (*int32, bool) {
	if o == nil || o.FirstOnPage == nil {
		return nil, false
	}
	return o.FirstOnPage, true
}

// HasFirstOnPage returns a boolean if a field has been set.
func (o *VariationPagination) HasFirstOnPage() bool {
	if o != nil && o.FirstOnPage != nil {
		return true
	}

	return false
}

// SetFirstOnPage gets a reference to the given int32 and assigns it to the FirstOnPage field.
func (o *VariationPagination) SetFirstOnPage(v int32) {
	o.FirstOnPage = &v
}

// GetLastOnPage returns the LastOnPage field value if set, zero value otherwise.
func (o *VariationPagination) GetLastOnPage() int32 {
	if o == nil || o.LastOnPage == nil {
		var ret int32
		return ret
	}
	return *o.LastOnPage
}

// GetLastOnPageOk returns a tuple with the LastOnPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariationPagination) GetLastOnPageOk() (*int32, bool) {
	if o == nil || o.LastOnPage == nil {
		return nil, false
	}
	return o.LastOnPage, true
}

// HasLastOnPage returns a boolean if a field has been set.
func (o *VariationPagination) HasLastOnPage() bool {
	if o != nil && o.LastOnPage != nil {
		return true
	}

	return false
}

// SetLastOnPage gets a reference to the given int32 and assigns it to the LastOnPage field.
func (o *VariationPagination) SetLastOnPage(v int32) {
	o.LastOnPage = &v
}

// GetItemsPerPage returns the ItemsPerPage field value if set, zero value otherwise.
func (o *VariationPagination) GetItemsPerPage() int32 {
	if o == nil || o.ItemsPerPage == nil {
		var ret int32
		return ret
	}
	return *o.ItemsPerPage
}

// GetItemsPerPageOk returns a tuple with the ItemsPerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariationPagination) GetItemsPerPageOk() (*int32, bool) {
	if o == nil || o.ItemsPerPage == nil {
		return nil, false
	}
	return o.ItemsPerPage, true
}

// HasItemsPerPage returns a boolean if a field has been set.
func (o *VariationPagination) HasItemsPerPage() bool {
	if o != nil && o.ItemsPerPage != nil {
		return true
	}

	return false
}

// SetItemsPerPage gets a reference to the given int32 and assigns it to the ItemsPerPage field.
func (o *VariationPagination) SetItemsPerPage(v int32) {
	o.ItemsPerPage = &v
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *VariationPagination) GetEntries() []Variation {
	if o == nil || o.Entries == nil {
		var ret []Variation
		return ret
	}
	return *o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariationPagination) GetEntriesOk() (*[]Variation, bool) {
	if o == nil || o.Entries == nil {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *VariationPagination) HasEntries() bool {
	if o != nil && o.Entries != nil {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []Variation and assigns it to the Entries field.
func (o *VariationPagination) SetEntries(v []Variation) {
	o.Entries = &v
}

func (o VariationPagination) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Page != nil {
		toSerialize["page"] = o.Page
	}
	if o.TotalsCount != nil {
		toSerialize["totalsCount"] = o.TotalsCount
	}
	if o.IsLastPage != nil {
		toSerialize["isLastPage"] = o.IsLastPage
	}
	if o.LastPageNumber != nil {
		toSerialize["lastPageNumber"] = o.LastPageNumber
	}
	if o.FirstOnPage != nil {
		toSerialize["firstOnPage"] = o.FirstOnPage
	}
	if o.LastOnPage != nil {
		toSerialize["lastOnPage"] = o.LastOnPage
	}
	if o.ItemsPerPage != nil {
		toSerialize["itemsPerPage"] = o.ItemsPerPage
	}
	if o.Entries != nil {
		toSerialize["entries"] = o.Entries
	}
	return json.Marshal(toSerialize)
}

type NullableVariationPagination struct {
	value *VariationPagination
	isSet bool
}

func (v NullableVariationPagination) Get() *VariationPagination {
	return v.value
}

func (v *NullableVariationPagination) Set(val *VariationPagination) {
	v.value = val
	v.isSet = true
}

func (v NullableVariationPagination) IsSet() bool {
	return v.isSet
}

func (v *NullableVariationPagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariationPagination(val *VariationPagination) *NullableVariationPagination {
	return &NullableVariationPagination{value: val, isSet: true}
}

func (v NullableVariationPagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariationPagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


