/*
Plentymarkets-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// PimVariationScrollResponse pagination response containing variations
type PimVariationScrollResponse struct {
	// The cursor for the next page of results.
	Cursor *string `json:"cursor,omitempty"`
	// List of Variation
	Entries *[]PimVariation `json:"entries,omitempty"`
}

// NewPimVariationScrollResponse instantiates a new PimVariationScrollResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPimVariationScrollResponse() *PimVariationScrollResponse {
	this := PimVariationScrollResponse{}
	return &this
}

// NewPimVariationScrollResponseWithDefaults instantiates a new PimVariationScrollResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPimVariationScrollResponseWithDefaults() *PimVariationScrollResponse {
	this := PimVariationScrollResponse{}
	return &this
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *PimVariationScrollResponse) GetCursor() string {
	if o == nil || o.Cursor == nil {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PimVariationScrollResponse) GetCursorOk() (*string, bool) {
	if o == nil || o.Cursor == nil {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *PimVariationScrollResponse) HasCursor() bool {
	if o != nil && o.Cursor != nil {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *PimVariationScrollResponse) SetCursor(v string) {
	o.Cursor = &v
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *PimVariationScrollResponse) GetEntries() []PimVariation {
	if o == nil || o.Entries == nil {
		var ret []PimVariation
		return ret
	}
	return *o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PimVariationScrollResponse) GetEntriesOk() (*[]PimVariation, bool) {
	if o == nil || o.Entries == nil {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *PimVariationScrollResponse) HasEntries() bool {
	if o != nil && o.Entries != nil {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []PimVariation and assigns it to the Entries field.
func (o *PimVariationScrollResponse) SetEntries(v []PimVariation) {
	o.Entries = &v
}

func (o PimVariationScrollResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Cursor != nil {
		toSerialize["cursor"] = o.Cursor
	}
	if o.Entries != nil {
		toSerialize["entries"] = o.Entries
	}
	return json.Marshal(toSerialize)
}

type NullablePimVariationScrollResponse struct {
	value *PimVariationScrollResponse
	isSet bool
}

func (v NullablePimVariationScrollResponse) Get() *PimVariationScrollResponse {
	return v.value
}

func (v *NullablePimVariationScrollResponse) Set(val *PimVariationScrollResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePimVariationScrollResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePimVariationScrollResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePimVariationScrollResponse(val *PimVariationScrollResponse) *NullablePimVariationScrollResponse {
	return &NullablePimVariationScrollResponse{value: val, isSet: true}
}

func (v NullablePimVariationScrollResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePimVariationScrollResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


