/*
Plentymarkets-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// Contact struct for Contact
type Contact struct {
	Id *int32 `json:"id,omitempty"`
	Number *string `json:"number,omitempty"`
	ExternalId *string `json:"externalId,omitempty"`
	TypeId *int32 `json:"typeId,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName *string `json:"lastName,omitempty"`
	Gender *string `json:"gender,omitempty"`
	Title *string `json:"title,omitempty"`
	FormOfAddress *string `json:"formOfAddress,omitempty"`
	NewsletterAllowanceAt *string `json:"newsletterAllowanceAt,omitempty"`
	ClassId *int32 `json:"classId,omitempty"`
	Blocked *int32 `json:"blocked,omitempty"`
	Rating *string `json:"rating,omitempty"`
	BookAccount *string `json:"bookAccount,omitempty"`
	Lang *string `json:"lang,omitempty"`
	ReferrerId *float32 `json:"referrerId,omitempty"`
	UserId *int32 `json:"userId,omitempty"`
	BirthdayAt *string `json:"birthdayAt,omitempty"`
	LastLoginAt *string `json:"lastLoginAt,omitempty"`
	LastOrderAt *string `json:"lastOrderAt,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Valuta *string `json:"valuta,omitempty"`
	IsLead *bool `json:"isLead,omitempty"`
	LeadStatusKey *string `json:"leadStatusKey,omitempty"`
	PlentyId *int32 `json:"plentyId,omitempty"`
	Email *string `json:"email,omitempty"`
	EbayName *string `json:"ebayName,omitempty"`
	PrivatePhone *string `json:"privatePhone,omitempty"`
	PrivateFax *string `json:"privateFax,omitempty"`
	PrivateMobile *string `json:"privateMobile,omitempty"`
	PaypalEmail *string `json:"paypalEmail,omitempty"`
	PaypalPayerId *string `json:"paypalPayerId,omitempty"`
	KlarnaPersonalId *string `json:"klarnaPersonalId,omitempty"`
	DhlPostIdent *string `json:"dhlPostIdent,omitempty"`
	SingleAccess *string `json:"singleAccess,omitempty"`
	ContactPerson *string `json:"contactPerson,omitempty"`
	MarketplacePartner *string `json:"marketplacePartner,omitempty"`
	FullName *string `json:"fullName,omitempty"`
	InLeadStatusSince *int32 `json:"inLeadStatusSince,omitempty"`
	Options *[]ContactOption `json:"options,omitempty"`
}

// NewContact instantiates a new Contact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContact() *Contact {
	this := Contact{}
	return &this
}

// NewContactWithDefaults instantiates a new Contact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactWithDefaults() *Contact {
	this := Contact{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Contact) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Contact) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Contact) SetId(v int32) {
	o.Id = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *Contact) GetNumber() string {
	if o == nil || o.Number == nil {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetNumberOk() (*string, bool) {
	if o == nil || o.Number == nil {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *Contact) HasNumber() bool {
	if o != nil && o.Number != nil {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *Contact) SetNumber(v string) {
	o.Number = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *Contact) GetExternalId() string {
	if o == nil || o.ExternalId == nil {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetExternalIdOk() (*string, bool) {
	if o == nil || o.ExternalId == nil {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *Contact) HasExternalId() bool {
	if o != nil && o.ExternalId != nil {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *Contact) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetTypeId returns the TypeId field value if set, zero value otherwise.
func (o *Contact) GetTypeId() int32 {
	if o == nil || o.TypeId == nil {
		var ret int32
		return ret
	}
	return *o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetTypeIdOk() (*int32, bool) {
	if o == nil || o.TypeId == nil {
		return nil, false
	}
	return o.TypeId, true
}

// HasTypeId returns a boolean if a field has been set.
func (o *Contact) HasTypeId() bool {
	if o != nil && o.TypeId != nil {
		return true
	}

	return false
}

// SetTypeId gets a reference to the given int32 and assigns it to the TypeId field.
func (o *Contact) SetTypeId(v int32) {
	o.TypeId = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *Contact) GetFirstName() string {
	if o == nil || o.FirstName == nil {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetFirstNameOk() (*string, bool) {
	if o == nil || o.FirstName == nil {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *Contact) HasFirstName() bool {
	if o != nil && o.FirstName != nil {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *Contact) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *Contact) GetLastName() string {
	if o == nil || o.LastName == nil {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetLastNameOk() (*string, bool) {
	if o == nil || o.LastName == nil {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *Contact) HasLastName() bool {
	if o != nil && o.LastName != nil {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *Contact) SetLastName(v string) {
	o.LastName = &v
}

// GetGender returns the Gender field value if set, zero value otherwise.
func (o *Contact) GetGender() string {
	if o == nil || o.Gender == nil {
		var ret string
		return ret
	}
	return *o.Gender
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetGenderOk() (*string, bool) {
	if o == nil || o.Gender == nil {
		return nil, false
	}
	return o.Gender, true
}

// HasGender returns a boolean if a field has been set.
func (o *Contact) HasGender() bool {
	if o != nil && o.Gender != nil {
		return true
	}

	return false
}

// SetGender gets a reference to the given string and assigns it to the Gender field.
func (o *Contact) SetGender(v string) {
	o.Gender = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Contact) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Contact) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Contact) SetTitle(v string) {
	o.Title = &v
}

// GetFormOfAddress returns the FormOfAddress field value if set, zero value otherwise.
func (o *Contact) GetFormOfAddress() string {
	if o == nil || o.FormOfAddress == nil {
		var ret string
		return ret
	}
	return *o.FormOfAddress
}

// GetFormOfAddressOk returns a tuple with the FormOfAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetFormOfAddressOk() (*string, bool) {
	if o == nil || o.FormOfAddress == nil {
		return nil, false
	}
	return o.FormOfAddress, true
}

// HasFormOfAddress returns a boolean if a field has been set.
func (o *Contact) HasFormOfAddress() bool {
	if o != nil && o.FormOfAddress != nil {
		return true
	}

	return false
}

// SetFormOfAddress gets a reference to the given string and assigns it to the FormOfAddress field.
func (o *Contact) SetFormOfAddress(v string) {
	o.FormOfAddress = &v
}

// GetNewsletterAllowanceAt returns the NewsletterAllowanceAt field value if set, zero value otherwise.
func (o *Contact) GetNewsletterAllowanceAt() string {
	if o == nil || o.NewsletterAllowanceAt == nil {
		var ret string
		return ret
	}
	return *o.NewsletterAllowanceAt
}

// GetNewsletterAllowanceAtOk returns a tuple with the NewsletterAllowanceAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetNewsletterAllowanceAtOk() (*string, bool) {
	if o == nil || o.NewsletterAllowanceAt == nil {
		return nil, false
	}
	return o.NewsletterAllowanceAt, true
}

// HasNewsletterAllowanceAt returns a boolean if a field has been set.
func (o *Contact) HasNewsletterAllowanceAt() bool {
	if o != nil && o.NewsletterAllowanceAt != nil {
		return true
	}

	return false
}

// SetNewsletterAllowanceAt gets a reference to the given string and assigns it to the NewsletterAllowanceAt field.
func (o *Contact) SetNewsletterAllowanceAt(v string) {
	o.NewsletterAllowanceAt = &v
}

// GetClassId returns the ClassId field value if set, zero value otherwise.
func (o *Contact) GetClassId() int32 {
	if o == nil || o.ClassId == nil {
		var ret int32
		return ret
	}
	return *o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetClassIdOk() (*int32, bool) {
	if o == nil || o.ClassId == nil {
		return nil, false
	}
	return o.ClassId, true
}

// HasClassId returns a boolean if a field has been set.
func (o *Contact) HasClassId() bool {
	if o != nil && o.ClassId != nil {
		return true
	}

	return false
}

// SetClassId gets a reference to the given int32 and assigns it to the ClassId field.
func (o *Contact) SetClassId(v int32) {
	o.ClassId = &v
}

// GetBlocked returns the Blocked field value if set, zero value otherwise.
func (o *Contact) GetBlocked() int32 {
	if o == nil || o.Blocked == nil {
		var ret int32
		return ret
	}
	return *o.Blocked
}

// GetBlockedOk returns a tuple with the Blocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetBlockedOk() (*int32, bool) {
	if o == nil || o.Blocked == nil {
		return nil, false
	}
	return o.Blocked, true
}

// HasBlocked returns a boolean if a field has been set.
func (o *Contact) HasBlocked() bool {
	if o != nil && o.Blocked != nil {
		return true
	}

	return false
}

// SetBlocked gets a reference to the given int32 and assigns it to the Blocked field.
func (o *Contact) SetBlocked(v int32) {
	o.Blocked = &v
}

// GetRating returns the Rating field value if set, zero value otherwise.
func (o *Contact) GetRating() string {
	if o == nil || o.Rating == nil {
		var ret string
		return ret
	}
	return *o.Rating
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetRatingOk() (*string, bool) {
	if o == nil || o.Rating == nil {
		return nil, false
	}
	return o.Rating, true
}

// HasRating returns a boolean if a field has been set.
func (o *Contact) HasRating() bool {
	if o != nil && o.Rating != nil {
		return true
	}

	return false
}

// SetRating gets a reference to the given string and assigns it to the Rating field.
func (o *Contact) SetRating(v string) {
	o.Rating = &v
}

// GetBookAccount returns the BookAccount field value if set, zero value otherwise.
func (o *Contact) GetBookAccount() string {
	if o == nil || o.BookAccount == nil {
		var ret string
		return ret
	}
	return *o.BookAccount
}

// GetBookAccountOk returns a tuple with the BookAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetBookAccountOk() (*string, bool) {
	if o == nil || o.BookAccount == nil {
		return nil, false
	}
	return o.BookAccount, true
}

// HasBookAccount returns a boolean if a field has been set.
func (o *Contact) HasBookAccount() bool {
	if o != nil && o.BookAccount != nil {
		return true
	}

	return false
}

// SetBookAccount gets a reference to the given string and assigns it to the BookAccount field.
func (o *Contact) SetBookAccount(v string) {
	o.BookAccount = &v
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *Contact) GetLang() string {
	if o == nil || o.Lang == nil {
		var ret string
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetLangOk() (*string, bool) {
	if o == nil || o.Lang == nil {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *Contact) HasLang() bool {
	if o != nil && o.Lang != nil {
		return true
	}

	return false
}

// SetLang gets a reference to the given string and assigns it to the Lang field.
func (o *Contact) SetLang(v string) {
	o.Lang = &v
}

// GetReferrerId returns the ReferrerId field value if set, zero value otherwise.
func (o *Contact) GetReferrerId() float32 {
	if o == nil || o.ReferrerId == nil {
		var ret float32
		return ret
	}
	return *o.ReferrerId
}

// GetReferrerIdOk returns a tuple with the ReferrerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetReferrerIdOk() (*float32, bool) {
	if o == nil || o.ReferrerId == nil {
		return nil, false
	}
	return o.ReferrerId, true
}

// HasReferrerId returns a boolean if a field has been set.
func (o *Contact) HasReferrerId() bool {
	if o != nil && o.ReferrerId != nil {
		return true
	}

	return false
}

// SetReferrerId gets a reference to the given float32 and assigns it to the ReferrerId field.
func (o *Contact) SetReferrerId(v float32) {
	o.ReferrerId = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *Contact) GetUserId() int32 {
	if o == nil || o.UserId == nil {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetUserIdOk() (*int32, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *Contact) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *Contact) SetUserId(v int32) {
	o.UserId = &v
}

// GetBirthdayAt returns the BirthdayAt field value if set, zero value otherwise.
func (o *Contact) GetBirthdayAt() string {
	if o == nil || o.BirthdayAt == nil {
		var ret string
		return ret
	}
	return *o.BirthdayAt
}

// GetBirthdayAtOk returns a tuple with the BirthdayAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetBirthdayAtOk() (*string, bool) {
	if o == nil || o.BirthdayAt == nil {
		return nil, false
	}
	return o.BirthdayAt, true
}

// HasBirthdayAt returns a boolean if a field has been set.
func (o *Contact) HasBirthdayAt() bool {
	if o != nil && o.BirthdayAt != nil {
		return true
	}

	return false
}

// SetBirthdayAt gets a reference to the given string and assigns it to the BirthdayAt field.
func (o *Contact) SetBirthdayAt(v string) {
	o.BirthdayAt = &v
}

// GetLastLoginAt returns the LastLoginAt field value if set, zero value otherwise.
func (o *Contact) GetLastLoginAt() string {
	if o == nil || o.LastLoginAt == nil {
		var ret string
		return ret
	}
	return *o.LastLoginAt
}

// GetLastLoginAtOk returns a tuple with the LastLoginAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetLastLoginAtOk() (*string, bool) {
	if o == nil || o.LastLoginAt == nil {
		return nil, false
	}
	return o.LastLoginAt, true
}

// HasLastLoginAt returns a boolean if a field has been set.
func (o *Contact) HasLastLoginAt() bool {
	if o != nil && o.LastLoginAt != nil {
		return true
	}

	return false
}

// SetLastLoginAt gets a reference to the given string and assigns it to the LastLoginAt field.
func (o *Contact) SetLastLoginAt(v string) {
	o.LastLoginAt = &v
}

// GetLastOrderAt returns the LastOrderAt field value if set, zero value otherwise.
func (o *Contact) GetLastOrderAt() string {
	if o == nil || o.LastOrderAt == nil {
		var ret string
		return ret
	}
	return *o.LastOrderAt
}

// GetLastOrderAtOk returns a tuple with the LastOrderAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetLastOrderAtOk() (*string, bool) {
	if o == nil || o.LastOrderAt == nil {
		return nil, false
	}
	return o.LastOrderAt, true
}

// HasLastOrderAt returns a boolean if a field has been set.
func (o *Contact) HasLastOrderAt() bool {
	if o != nil && o.LastOrderAt != nil {
		return true
	}

	return false
}

// SetLastOrderAt gets a reference to the given string and assigns it to the LastOrderAt field.
func (o *Contact) SetLastOrderAt(v string) {
	o.LastOrderAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Contact) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Contact) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *Contact) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Contact) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Contact) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *Contact) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetValuta returns the Valuta field value if set, zero value otherwise.
func (o *Contact) GetValuta() string {
	if o == nil || o.Valuta == nil {
		var ret string
		return ret
	}
	return *o.Valuta
}

// GetValutaOk returns a tuple with the Valuta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetValutaOk() (*string, bool) {
	if o == nil || o.Valuta == nil {
		return nil, false
	}
	return o.Valuta, true
}

// HasValuta returns a boolean if a field has been set.
func (o *Contact) HasValuta() bool {
	if o != nil && o.Valuta != nil {
		return true
	}

	return false
}

// SetValuta gets a reference to the given string and assigns it to the Valuta field.
func (o *Contact) SetValuta(v string) {
	o.Valuta = &v
}

// GetIsLead returns the IsLead field value if set, zero value otherwise.
func (o *Contact) GetIsLead() bool {
	if o == nil || o.IsLead == nil {
		var ret bool
		return ret
	}
	return *o.IsLead
}

// GetIsLeadOk returns a tuple with the IsLead field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetIsLeadOk() (*bool, bool) {
	if o == nil || o.IsLead == nil {
		return nil, false
	}
	return o.IsLead, true
}

// HasIsLead returns a boolean if a field has been set.
func (o *Contact) HasIsLead() bool {
	if o != nil && o.IsLead != nil {
		return true
	}

	return false
}

// SetIsLead gets a reference to the given bool and assigns it to the IsLead field.
func (o *Contact) SetIsLead(v bool) {
	o.IsLead = &v
}

// GetLeadStatusKey returns the LeadStatusKey field value if set, zero value otherwise.
func (o *Contact) GetLeadStatusKey() string {
	if o == nil || o.LeadStatusKey == nil {
		var ret string
		return ret
	}
	return *o.LeadStatusKey
}

// GetLeadStatusKeyOk returns a tuple with the LeadStatusKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetLeadStatusKeyOk() (*string, bool) {
	if o == nil || o.LeadStatusKey == nil {
		return nil, false
	}
	return o.LeadStatusKey, true
}

// HasLeadStatusKey returns a boolean if a field has been set.
func (o *Contact) HasLeadStatusKey() bool {
	if o != nil && o.LeadStatusKey != nil {
		return true
	}

	return false
}

// SetLeadStatusKey gets a reference to the given string and assigns it to the LeadStatusKey field.
func (o *Contact) SetLeadStatusKey(v string) {
	o.LeadStatusKey = &v
}

// GetPlentyId returns the PlentyId field value if set, zero value otherwise.
func (o *Contact) GetPlentyId() int32 {
	if o == nil || o.PlentyId == nil {
		var ret int32
		return ret
	}
	return *o.PlentyId
}

// GetPlentyIdOk returns a tuple with the PlentyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetPlentyIdOk() (*int32, bool) {
	if o == nil || o.PlentyId == nil {
		return nil, false
	}
	return o.PlentyId, true
}

// HasPlentyId returns a boolean if a field has been set.
func (o *Contact) HasPlentyId() bool {
	if o != nil && o.PlentyId != nil {
		return true
	}

	return false
}

// SetPlentyId gets a reference to the given int32 and assigns it to the PlentyId field.
func (o *Contact) SetPlentyId(v int32) {
	o.PlentyId = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *Contact) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *Contact) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *Contact) SetEmail(v string) {
	o.Email = &v
}

// GetEbayName returns the EbayName field value if set, zero value otherwise.
func (o *Contact) GetEbayName() string {
	if o == nil || o.EbayName == nil {
		var ret string
		return ret
	}
	return *o.EbayName
}

// GetEbayNameOk returns a tuple with the EbayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetEbayNameOk() (*string, bool) {
	if o == nil || o.EbayName == nil {
		return nil, false
	}
	return o.EbayName, true
}

// HasEbayName returns a boolean if a field has been set.
func (o *Contact) HasEbayName() bool {
	if o != nil && o.EbayName != nil {
		return true
	}

	return false
}

// SetEbayName gets a reference to the given string and assigns it to the EbayName field.
func (o *Contact) SetEbayName(v string) {
	o.EbayName = &v
}

// GetPrivatePhone returns the PrivatePhone field value if set, zero value otherwise.
func (o *Contact) GetPrivatePhone() string {
	if o == nil || o.PrivatePhone == nil {
		var ret string
		return ret
	}
	return *o.PrivatePhone
}

// GetPrivatePhoneOk returns a tuple with the PrivatePhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetPrivatePhoneOk() (*string, bool) {
	if o == nil || o.PrivatePhone == nil {
		return nil, false
	}
	return o.PrivatePhone, true
}

// HasPrivatePhone returns a boolean if a field has been set.
func (o *Contact) HasPrivatePhone() bool {
	if o != nil && o.PrivatePhone != nil {
		return true
	}

	return false
}

// SetPrivatePhone gets a reference to the given string and assigns it to the PrivatePhone field.
func (o *Contact) SetPrivatePhone(v string) {
	o.PrivatePhone = &v
}

// GetPrivateFax returns the PrivateFax field value if set, zero value otherwise.
func (o *Contact) GetPrivateFax() string {
	if o == nil || o.PrivateFax == nil {
		var ret string
		return ret
	}
	return *o.PrivateFax
}

// GetPrivateFaxOk returns a tuple with the PrivateFax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetPrivateFaxOk() (*string, bool) {
	if o == nil || o.PrivateFax == nil {
		return nil, false
	}
	return o.PrivateFax, true
}

// HasPrivateFax returns a boolean if a field has been set.
func (o *Contact) HasPrivateFax() bool {
	if o != nil && o.PrivateFax != nil {
		return true
	}

	return false
}

// SetPrivateFax gets a reference to the given string and assigns it to the PrivateFax field.
func (o *Contact) SetPrivateFax(v string) {
	o.PrivateFax = &v
}

// GetPrivateMobile returns the PrivateMobile field value if set, zero value otherwise.
func (o *Contact) GetPrivateMobile() string {
	if o == nil || o.PrivateMobile == nil {
		var ret string
		return ret
	}
	return *o.PrivateMobile
}

// GetPrivateMobileOk returns a tuple with the PrivateMobile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetPrivateMobileOk() (*string, bool) {
	if o == nil || o.PrivateMobile == nil {
		return nil, false
	}
	return o.PrivateMobile, true
}

// HasPrivateMobile returns a boolean if a field has been set.
func (o *Contact) HasPrivateMobile() bool {
	if o != nil && o.PrivateMobile != nil {
		return true
	}

	return false
}

// SetPrivateMobile gets a reference to the given string and assigns it to the PrivateMobile field.
func (o *Contact) SetPrivateMobile(v string) {
	o.PrivateMobile = &v
}

// GetPaypalEmail returns the PaypalEmail field value if set, zero value otherwise.
func (o *Contact) GetPaypalEmail() string {
	if o == nil || o.PaypalEmail == nil {
		var ret string
		return ret
	}
	return *o.PaypalEmail
}

// GetPaypalEmailOk returns a tuple with the PaypalEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetPaypalEmailOk() (*string, bool) {
	if o == nil || o.PaypalEmail == nil {
		return nil, false
	}
	return o.PaypalEmail, true
}

// HasPaypalEmail returns a boolean if a field has been set.
func (o *Contact) HasPaypalEmail() bool {
	if o != nil && o.PaypalEmail != nil {
		return true
	}

	return false
}

// SetPaypalEmail gets a reference to the given string and assigns it to the PaypalEmail field.
func (o *Contact) SetPaypalEmail(v string) {
	o.PaypalEmail = &v
}

// GetPaypalPayerId returns the PaypalPayerId field value if set, zero value otherwise.
func (o *Contact) GetPaypalPayerId() string {
	if o == nil || o.PaypalPayerId == nil {
		var ret string
		return ret
	}
	return *o.PaypalPayerId
}

// GetPaypalPayerIdOk returns a tuple with the PaypalPayerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetPaypalPayerIdOk() (*string, bool) {
	if o == nil || o.PaypalPayerId == nil {
		return nil, false
	}
	return o.PaypalPayerId, true
}

// HasPaypalPayerId returns a boolean if a field has been set.
func (o *Contact) HasPaypalPayerId() bool {
	if o != nil && o.PaypalPayerId != nil {
		return true
	}

	return false
}

// SetPaypalPayerId gets a reference to the given string and assigns it to the PaypalPayerId field.
func (o *Contact) SetPaypalPayerId(v string) {
	o.PaypalPayerId = &v
}

// GetKlarnaPersonalId returns the KlarnaPersonalId field value if set, zero value otherwise.
func (o *Contact) GetKlarnaPersonalId() string {
	if o == nil || o.KlarnaPersonalId == nil {
		var ret string
		return ret
	}
	return *o.KlarnaPersonalId
}

// GetKlarnaPersonalIdOk returns a tuple with the KlarnaPersonalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetKlarnaPersonalIdOk() (*string, bool) {
	if o == nil || o.KlarnaPersonalId == nil {
		return nil, false
	}
	return o.KlarnaPersonalId, true
}

// HasKlarnaPersonalId returns a boolean if a field has been set.
func (o *Contact) HasKlarnaPersonalId() bool {
	if o != nil && o.KlarnaPersonalId != nil {
		return true
	}

	return false
}

// SetKlarnaPersonalId gets a reference to the given string and assigns it to the KlarnaPersonalId field.
func (o *Contact) SetKlarnaPersonalId(v string) {
	o.KlarnaPersonalId = &v
}

// GetDhlPostIdent returns the DhlPostIdent field value if set, zero value otherwise.
func (o *Contact) GetDhlPostIdent() string {
	if o == nil || o.DhlPostIdent == nil {
		var ret string
		return ret
	}
	return *o.DhlPostIdent
}

// GetDhlPostIdentOk returns a tuple with the DhlPostIdent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetDhlPostIdentOk() (*string, bool) {
	if o == nil || o.DhlPostIdent == nil {
		return nil, false
	}
	return o.DhlPostIdent, true
}

// HasDhlPostIdent returns a boolean if a field has been set.
func (o *Contact) HasDhlPostIdent() bool {
	if o != nil && o.DhlPostIdent != nil {
		return true
	}

	return false
}

// SetDhlPostIdent gets a reference to the given string and assigns it to the DhlPostIdent field.
func (o *Contact) SetDhlPostIdent(v string) {
	o.DhlPostIdent = &v
}

// GetSingleAccess returns the SingleAccess field value if set, zero value otherwise.
func (o *Contact) GetSingleAccess() string {
	if o == nil || o.SingleAccess == nil {
		var ret string
		return ret
	}
	return *o.SingleAccess
}

// GetSingleAccessOk returns a tuple with the SingleAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetSingleAccessOk() (*string, bool) {
	if o == nil || o.SingleAccess == nil {
		return nil, false
	}
	return o.SingleAccess, true
}

// HasSingleAccess returns a boolean if a field has been set.
func (o *Contact) HasSingleAccess() bool {
	if o != nil && o.SingleAccess != nil {
		return true
	}

	return false
}

// SetSingleAccess gets a reference to the given string and assigns it to the SingleAccess field.
func (o *Contact) SetSingleAccess(v string) {
	o.SingleAccess = &v
}

// GetContactPerson returns the ContactPerson field value if set, zero value otherwise.
func (o *Contact) GetContactPerson() string {
	if o == nil || o.ContactPerson == nil {
		var ret string
		return ret
	}
	return *o.ContactPerson
}

// GetContactPersonOk returns a tuple with the ContactPerson field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetContactPersonOk() (*string, bool) {
	if o == nil || o.ContactPerson == nil {
		return nil, false
	}
	return o.ContactPerson, true
}

// HasContactPerson returns a boolean if a field has been set.
func (o *Contact) HasContactPerson() bool {
	if o != nil && o.ContactPerson != nil {
		return true
	}

	return false
}

// SetContactPerson gets a reference to the given string and assigns it to the ContactPerson field.
func (o *Contact) SetContactPerson(v string) {
	o.ContactPerson = &v
}

// GetMarketplacePartner returns the MarketplacePartner field value if set, zero value otherwise.
func (o *Contact) GetMarketplacePartner() string {
	if o == nil || o.MarketplacePartner == nil {
		var ret string
		return ret
	}
	return *o.MarketplacePartner
}

// GetMarketplacePartnerOk returns a tuple with the MarketplacePartner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetMarketplacePartnerOk() (*string, bool) {
	if o == nil || o.MarketplacePartner == nil {
		return nil, false
	}
	return o.MarketplacePartner, true
}

// HasMarketplacePartner returns a boolean if a field has been set.
func (o *Contact) HasMarketplacePartner() bool {
	if o != nil && o.MarketplacePartner != nil {
		return true
	}

	return false
}

// SetMarketplacePartner gets a reference to the given string and assigns it to the MarketplacePartner field.
func (o *Contact) SetMarketplacePartner(v string) {
	o.MarketplacePartner = &v
}

// GetFullName returns the FullName field value if set, zero value otherwise.
func (o *Contact) GetFullName() string {
	if o == nil || o.FullName == nil {
		var ret string
		return ret
	}
	return *o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetFullNameOk() (*string, bool) {
	if o == nil || o.FullName == nil {
		return nil, false
	}
	return o.FullName, true
}

// HasFullName returns a boolean if a field has been set.
func (o *Contact) HasFullName() bool {
	if o != nil && o.FullName != nil {
		return true
	}

	return false
}

// SetFullName gets a reference to the given string and assigns it to the FullName field.
func (o *Contact) SetFullName(v string) {
	o.FullName = &v
}

// GetInLeadStatusSince returns the InLeadStatusSince field value if set, zero value otherwise.
func (o *Contact) GetInLeadStatusSince() int32 {
	if o == nil || o.InLeadStatusSince == nil {
		var ret int32
		return ret
	}
	return *o.InLeadStatusSince
}

// GetInLeadStatusSinceOk returns a tuple with the InLeadStatusSince field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetInLeadStatusSinceOk() (*int32, bool) {
	if o == nil || o.InLeadStatusSince == nil {
		return nil, false
	}
	return o.InLeadStatusSince, true
}

// HasInLeadStatusSince returns a boolean if a field has been set.
func (o *Contact) HasInLeadStatusSince() bool {
	if o != nil && o.InLeadStatusSince != nil {
		return true
	}

	return false
}

// SetInLeadStatusSince gets a reference to the given int32 and assigns it to the InLeadStatusSince field.
func (o *Contact) SetInLeadStatusSince(v int32) {
	o.InLeadStatusSince = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *Contact) GetOptions() []ContactOption {
	if o == nil || o.Options == nil {
		var ret []ContactOption
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contact) GetOptionsOk() (*[]ContactOption, bool) {
	if o == nil || o.Options == nil {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *Contact) HasOptions() bool {
	if o != nil && o.Options != nil {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []ContactOption and assigns it to the Options field.
func (o *Contact) SetOptions(v []ContactOption) {
	o.Options = &v
}

func (o Contact) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Number != nil {
		toSerialize["number"] = o.Number
	}
	if o.ExternalId != nil {
		toSerialize["externalId"] = o.ExternalId
	}
	if o.TypeId != nil {
		toSerialize["typeId"] = o.TypeId
	}
	if o.FirstName != nil {
		toSerialize["firstName"] = o.FirstName
	}
	if o.LastName != nil {
		toSerialize["lastName"] = o.LastName
	}
	if o.Gender != nil {
		toSerialize["gender"] = o.Gender
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.FormOfAddress != nil {
		toSerialize["formOfAddress"] = o.FormOfAddress
	}
	if o.NewsletterAllowanceAt != nil {
		toSerialize["newsletterAllowanceAt"] = o.NewsletterAllowanceAt
	}
	if o.ClassId != nil {
		toSerialize["classId"] = o.ClassId
	}
	if o.Blocked != nil {
		toSerialize["blocked"] = o.Blocked
	}
	if o.Rating != nil {
		toSerialize["rating"] = o.Rating
	}
	if o.BookAccount != nil {
		toSerialize["bookAccount"] = o.BookAccount
	}
	if o.Lang != nil {
		toSerialize["lang"] = o.Lang
	}
	if o.ReferrerId != nil {
		toSerialize["referrerId"] = o.ReferrerId
	}
	if o.UserId != nil {
		toSerialize["userId"] = o.UserId
	}
	if o.BirthdayAt != nil {
		toSerialize["birthdayAt"] = o.BirthdayAt
	}
	if o.LastLoginAt != nil {
		toSerialize["lastLoginAt"] = o.LastLoginAt
	}
	if o.LastOrderAt != nil {
		toSerialize["lastOrderAt"] = o.LastOrderAt
	}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.Valuta != nil {
		toSerialize["valuta"] = o.Valuta
	}
	if o.IsLead != nil {
		toSerialize["isLead"] = o.IsLead
	}
	if o.LeadStatusKey != nil {
		toSerialize["leadStatusKey"] = o.LeadStatusKey
	}
	if o.PlentyId != nil {
		toSerialize["plentyId"] = o.PlentyId
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.EbayName != nil {
		toSerialize["ebayName"] = o.EbayName
	}
	if o.PrivatePhone != nil {
		toSerialize["privatePhone"] = o.PrivatePhone
	}
	if o.PrivateFax != nil {
		toSerialize["privateFax"] = o.PrivateFax
	}
	if o.PrivateMobile != nil {
		toSerialize["privateMobile"] = o.PrivateMobile
	}
	if o.PaypalEmail != nil {
		toSerialize["paypalEmail"] = o.PaypalEmail
	}
	if o.PaypalPayerId != nil {
		toSerialize["paypalPayerId"] = o.PaypalPayerId
	}
	if o.KlarnaPersonalId != nil {
		toSerialize["klarnaPersonalId"] = o.KlarnaPersonalId
	}
	if o.DhlPostIdent != nil {
		toSerialize["dhlPostIdent"] = o.DhlPostIdent
	}
	if o.SingleAccess != nil {
		toSerialize["singleAccess"] = o.SingleAccess
	}
	if o.ContactPerson != nil {
		toSerialize["contactPerson"] = o.ContactPerson
	}
	if o.MarketplacePartner != nil {
		toSerialize["marketplacePartner"] = o.MarketplacePartner
	}
	if o.FullName != nil {
		toSerialize["fullName"] = o.FullName
	}
	if o.InLeadStatusSince != nil {
		toSerialize["inLeadStatusSince"] = o.InLeadStatusSince
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableContact struct {
	value *Contact
	isSet bool
}

func (v NullableContact) Get() *Contact {
	return v.value
}

func (v *NullableContact) Set(val *Contact) {
	v.value = val
	v.isSet = true
}

func (v NullableContact) IsSet() bool {
	return v.isSet
}

func (v *NullableContact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContact(val *Contact) *NullableContact {
	return &NullableContact{value: val, isSet: true}
}

func (v NullableContact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


